# Generated by Django 4.0 on 2023-08-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=250)),
                ('currdate', models.DateField()),
            ],
        ),
    ]
