# Generated by Django 4.0 on 2023-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_rename_logs_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
                ('type', models.TextField()),
                ('message', models.TextField()),
                ('currdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
