# Generated by Django 4.0 on 2023-09-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_logs_delete_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
